project_id = "ucaomurffgvkaivttyfc"

[functions.generate-image]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.generate-email]
verify_jwt = true

[functions.send-campaign]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = true

[functions.subscribe]
verify_jwt = false
